sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper

install:
  - ./mvnw --show-version -Dbuildtime.output.log
    -Plight-psi -DskipMain clean install

script: # build sequentially - epigraph-maven-plugin (light-psi) is not thread-safe :(
  - ./mvnw --show-version -Dbuildtime.output.log
    clean
    -Djacoco.append -Djacoco.destFile="$(pwd)/target/jacoco.exec" org.jacoco:jacoco-maven-plugin:prepare-agent
    test

# TODO run gradle build as well?

# Remove any Epigraph project artifacts (that change from build to build) from cached local repository:
before_cache:
  - rm -rf $HOME/.m2/repository/ws/epigraph

after_success:
  - ./mvnw --show-version
    -T8 -Djacoco.dataFile="$(pwd)/target/jacoco.exec" org.jacoco:jacoco-maven-plugin:report
  - bash <(curl -s https://codecov.io/bash)
