sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper

install: ./mvnw --show-version install -Plight-psi

script: ./mvnw --show-version -Dbuildtime.output.log test

# TODO run gradle build as well?

before_cache:
  - rm -rf $HOME/.m2/repository/ws/epigraph
