sudo: required

language: java
jdk: oraclejdk8

install: ./mvnw --show-version --batch-mode clean install -Plight-psi

script: ./mvnw --batch-mode clean test

# TODO run gradle build as well?

cache:
  directories:
    - $HOME/.m2
