sudo: required

language: java
jdk: oraclejdk8

install: ./mvnw --batch-mode install -Plight-psi

script: ./mvnw --show-version -Dbuildtime.output.log test

# TODO run gradle build as well?

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper
