sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper

install: true

script: ./mvnw --show-version -Dbuildtime.output.log -Plight-psi
  clean
  org.jacoco:jacoco-maven-plugin:prepare-agent
  test
  org.jacoco:jacoco-maven-plugin:report-aggregate

# TODO run gradle build as well?

# Remove any Epigrph project artifacts (that change from build to build) from cached local repository:
before_cache:
  - rm -rf $HOME/.m2/repository/ws/epigraph

after_success:
  - bash <(curl -s https://codecov.io/bash)
