sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper

install: ./mvnw --show-version install -Plight-psi,-main # TODO light-psi install is no longer needed, move to script

script: ./mvnw --show-version -Dbuildtime.output.log
  clean
  org.jacoco:jacoco-maven-plugin:prepare-agent
  test
  org.jacoco:jacoco-maven-plugin:report-aggregate

# TODO run gradle build as well?

before_cache:
  - rm -rf $HOME/.m2/repository/ws/epigraph

after_success:
  - bash <(curl -s https://codecov.io/bash)
