{
  parserClass="io.epigraph.idl.parser.IdlParser"

  elementTypeHolderClass="io.epigraph.idl.lexer.IdlElementTypes"
  elementTypePrefix="I_"
  elementTypeClass="io.epigraph.idl.lexer.IdlElementType"
  tokenTypeClass="io.epigraph.idl.lexer.IdlElementType"

  psiClassPrefix="Idl"
  psiImplClassSuffix="Impl"
  psiPackage="io.epigraph.idl.parser.psi"
  psiImplPackage="io.epigraph.idl.parser.psi.impl"
  psiImplUtilClass="io.epigraph.idl.parser.psi.impl.IdlPsiImplUtil"

  generateTokenAccessors=true

  tokens=[
    NAMESPACE = 'namespace'
    IMPORT = 'import'
    FORBIDDEN = 'forbidden'
    REQURIED = 'required'
    PARAMETERS = 'parameters'
    DEFAULT = 'default'
//    PRIMITIVE = 'primitive'
//    ENUM = 'enum'

    COLON = ':'
    DOT = '.'
    COMMA = ','
    SEMICOLON = ';'
    EQ = '='
    CURLY_LEFT = '{'
    CURLY_RIGHT = '}'
    BRACKET_LEFT = '['
    BRACKET_RIGHT = ']'
    TILDA = '~'
    STAR = '*'
    PLUS = '+'
    AT = '@'
    UNDERSCORE = '_'

    space='regexp:\s+'
    comment='regexp://.*'
    block_comment='regexp:/\*((?<!\*/)(.|\n))*'

    id = 'regexp:(\p{Alpha}\p{Alnum}*)|(`([^`]*)`)'

    // for data lang
    NULL = 'null'
    SLASH = '/'
    PAREN_LEFT = '('
    PAREN_RIGHT = ')'
    ANGLE_LEFT = '<'
    ANGLE_RIGHT = '>'

    number="regexp:([0-9])+"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    boolean="regexp:true|false"
  ]

  pin(".*Body") = 1
}

// TODO proper root
root ::= namespaceDecl imports opOutputVarProjection

// either quoted or unquoted id
qid ::= id {
//   methods=[getName setName getCanonicalName]
   methods=[getName getCanonicalName]
}

imports ::= importStatement*
importStatement ::= 'import' fqn {pin=1 recoverWhile="importRecover"}

namespaceDecl ::= 'namespace' fqn namespaceBody? {
//  methods=[getFqn2 toString]
//  stubClass="io.epigraph.schema.parser.psi.stubs.SchemaNamespaceDeclStub"
//  elementTypeClass="io.epigraph.schema.parser.psi.stubs.SchemaNamespaceDeclStubElementType"
  pin=1
  recoverWhile="namespaceDeclRecover"
}

private namespaceBody ::= '{' namespaceBodyPart* '}'
private namespaceBodyPart ::= customParam // | ...

fqnSegment ::= qid {
//  implements="com.intellij.psi.PsiNameIdentifierOwner"
//  methods=[getName setName getNameIdentifier getSchemaFqn getSchemaFqnTypeRef isLast getReference getFqn]
}
fqn ::= fqnSegment ('.' fqnSegment)* {
  methods=[getFqn]
}

fqnTypeRef ::= fqn {
  name="type"
//  methods=[resolve] extends="typeRef"
}

//varTagRef ::= qid {
//  implements="com.intellij.psi.PsiNameIdentifierOwner"
////  methods=[setName getNameIdentifier getReference]
//}

customParam ::= qid '=' dataValue {
  name="custom attribute"
//  implements="com.intellij.psi.PsiNamedElement"
//  methods = [getName setName getNameIdentifier]
  pin = 2
}

private namespaceDeclRecover ::= ! ('import' | 'namespace' )
private importRecover ::= namespaceDeclRecover

// ------------- op projections -------------

opTagName ::= qid | '_' // `_` is default tag

// output

opParam ::= ';' '+'? qid ':' fqnTypeRef opInputModelProjection ( '=' varValue )?

opOutputVarProjection ::= ( opOutputMultiTagProjection | opOutputSingleTagProjection ) opOutputVarPolymorphicTail?

opOutputSingleTagProjection ::= ( ':' '+'? opTagName)? (opOutputComplexSingleTagProjection | opOutputSimpleSingleTagProjection )
private opOutputSimpleSingleTagProjection ::= opOutputModelProjection
private opOutputComplexSingleTagProjection ::= '{' (opOutputModelProperty ','?)* opOutputModelProjection '}' {pin=1}

opOutputMultiTagProjection ::= ':' '(' (opOutputMultiTagProjectionItem ','?)* ')' {pin=2}
opOutputMultiTagProjectionItem ::= '+'? opTagName ( opOutputComplexMultiTagProjectionItem | opOutputSimpleMultiTagProjectionItem )
private opOutputSimpleMultiTagProjectionItem ::= opOutputModelProjection
private opOutputComplexMultiTagProjectionItem ::= '{' (opOutputModelProperty ','?)* opOutputModelProjection '}' {pin=1}
//
opOutputVarPolymorphicTail ::= opOutputVarSingleTail | opOutputVarMultiTail
opOutputVarSingleTail ::= '~' fqnTypeRef opOutputVarProjection
opOutputVarMultiTail ::= '~' '(' (opOutputVarMultiTailItem ','?)* ')' {pin=2}
opOutputVarMultiTailItem ::= fqnTypeRef opOutputVarProjection

opOutputModelProperty ::= opParam | customParam

opOutputModelProjection ::= ( opOutputRecordModelProjection
                            | opOutputListModelProjection
                            | opOutputMapModelProjection
//                          | opOutputEnumModelProjection
//                          | opOutputPrimitiveModelProjection
                            )?

// op output record
opOutputRecordModelProjection ::= '(' (opOutputFieldProjection ','?)* ')' { pin=1 }
opOutputFieldProjection ::= '+'? qid (opOutputComplexFieldProjection | opOutputSimpleFieldProjection)
private opOutputComplexFieldProjection ::= '{' (opOutputFieldProjectionBodyPart ','? )* opOutputVarProjection? '}'
private opOutputSimpleFieldProjection ::= opOutputVarProjection
opOutputFieldProjectionBodyPart ::= opParam | customParam

// op output list
opOutputListModelProjection ::= '*' '(' opOutputVarProjection ')' { pin=1 }

opOutputMapModelProjection ::= opOutputKeyProjection '(' opOutputVarProjection ')' { pin=1 }
opOutputKeyProjection ::= '[' ('required' ','?| 'forbidden' ','?)? (opOutputKeyProjectionPart ','?)* ']' {pin=1}
opOutputKeyProjectionPart ::= opParam | customParam

//opOutputPrimitiveModelProjection ::= 'primitive' // ?
//opOutputEnumModelProjection ::= 'enum' // ?

// input

opInputVarProjection ::= ( opInputMultiTagProjection | opInputSingleTagProjection ) opInputVarPolymorphicTail?
opInputSingleTagProjection ::= ( ':' '+'? opTagName)? (opInputComplexSingleTagProjection | opInputSimpleSingleTagProjection )
private opInputSimpleSingleTagProjection ::= opInputModelProjection
private opInputComplexSingleTagProjection ::= '{' (opInputModelProperty ','?)* opInputModelProjection '}' {pin=1}

opInputMultiTagProjection ::= ':' '(' (opInputMultiTagProjectionItem ','?)* ')' {pin=2}
opInputMultiTagProjectionItem ::= '+'? opTagName ( opInputComplexMultiTagProjectionItem | opInputSimpleMultiTagProjectionItem )
private opInputSimpleMultiTagProjectionItem ::= opInputModelProjection
private opInputComplexMultiTagProjectionItem ::= '{' (opInputModelProperty ','?)* opInputModelProjection '}' {pin=1}
//
opInputVarPolymorphicTail ::= opInputVarSingleTail | opInputVarMultiTail
opInputVarSingleTail ::= '~' fqnTypeRef opInputVarProjection
opInputVarMultiTail ::= '~' '(' (opInputVarMultiTailItem ','?)* ')' {pin=2}
opInputVarMultiTailItem ::= fqnTypeRef opInputVarProjection

opInputModelProperty ::= opInputDefaultValue | customParam
opInputDefaultValue ::= 'default' ':' varValue {pin=1}

opInputModelProjection ::= ( opInputRecordModelProjection
                           | opInputListModelProjection
                           | opInputMapModelProjection
//                         | opInputEnumModelProjection
//                         | opInputPrimitiveModelProjection
                           )?

// op input record
opInputRecordModelProjection ::= '(' (opInputFieldProjection ','?)* ')' { pin=1 }
opInputFieldProjection ::= '+'? qid (opInputComplexFieldProjection | opInputSimpleFieldProjection)
private opInputComplexFieldProjection ::= '{' (opInputFieldProjectionBodyPart ','? )* opInputVarProjection? '}'
private opInputSimpleFieldProjection ::= opInputVarProjection
opInputFieldProjectionBodyPart ::= customParam

// op input list
opInputListModelProjection ::= '*' '(' opInputVarProjection ')' { pin=1 }

opInputMapModelProjection ::= opInputKeyProjection '(' opInputVarProjection ')' { pin=1 }
opInputKeyProjection ::= '[' (opInputKeyProjectionPart ','?)* ']' {pin=1}
opInputKeyProjectionPart ::= 'forbidden' | 'required' | customParam

//opInputPrimitiveModelProjection ::= 'primitive' // ?
//opInputEnumModelProjection ::= 'enum' // ?

// ------------- data language -------------

dataValue ::= dataVar | varValue
private dataTypeSpec ::= fqnTypeRef

dataVar ::= dataTypeSpec? '<' dataVarEntry* '>' {pin=2}
dataVarEntry ::= qid ':' varValue ','? {pin=2 recoverWhile=dataValueRecover}

varValue ::= dataRecord | dataMap | dataList | dataPrimitive | dataEnum | dataNull

dataRecord ::= dataTypeSpec? '{' dataRecordEntry* '}' {pin=2 extends=varValue}
dataRecordEntry ::= qid ':' dataValue ','? {pin=2 recoverWhile=dataValueRecover}

dataMap ::= dataTypeSpec? '(' dataMapEntry* ')' {pin=2 extends=varValue}
dataMapEntry ::= varValue ':' dataValue ','? {pin=2 recoverWhile=dataValueRecover}

dataList ::= dataTypeSpec? '[' (dataValue ','?)* ']' {pin=2 extends=varValue}

dataPrimitive ::= (dataTypeSpec '@')? (string | number | boolean) {extends=varValue}

dataEnum ::= qid {extends=varValue}

dataNull ::= dataSpeccedNull | dataUnspeccedNull {extends=varValue}
private dataSpeccedNull ::= dataTypeSpec '(' dataUnspeccedNull ')'
private dataUnspeccedNull ::= 'null'

private dataValueRecover ::= ! ( qid | dataPrimitive | '}' | ')' | '>' | ']' | ',' )
